# Generated by Django 2.2.19 on 2021-02-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sample',
            new_name='Room',
        ),
    ]
